all:
	pandoc abstract.md -o abstract.tex
	pandoc domain-mismatch.md -o domain-mismatch.tex
	pandoc whiteners-library.md -o whiteners-library.tex
	pandoc dicn.md -o dicn.tex
	pandoc evaluation.md -o evaluation.tex
	pandoc results.md -o results.tex
	pdflatex src.tex
